### ISSUE TITLE
Cannot leave/dismount boats with beta of RootsClassic installed

### ISSUE THREAD

**Issue by TranquilStar** [ZestyBlaze/RootsClassic#3]
It didnt give a log on what caused the issue or a crash log (the game doesnt crash so makes sense)

I dont know if its a mod incomaptability or something, but whenever this mod is installed it breaks minecraft boats (non and even modded)

when the boat breaks the camera breaks moving rapidly until death, I thought it was another mod but after heavy troubleshooting and testing I can safely say for certain this mod is the issue

[MODLIST.txt](https://github.com/ZestyBlaze/RootsClassic/files/12191011/MODLIST.txt)

**Comment by TranquilStar** [comment]
the provided modlist was made with notepad btw, and does not have the rootsclassic mod added

**Comment by ZestyBlaze** [comment]
What's the Minecraft version? 1.19 or 1.20?

**Comment by ZestyBlaze** [comment]
Fixed in Version 1.2.1 going up live now on Curseforge: [Link](https://legacy.curseforge.com/minecraft/mc-mods/roots-classic-fabric/files/4675070) (Will need to finish approving)
