### ISSUE TITLE
Mod do crazy memory leak

### ISSUE THREAD

**Issue by mindryder** [ZestyBlaze/RootsClassic#9]
That crazy, check. 

Without roots (main game menu):
![OGdVr1cBrv](https://github.com/ZestyBlaze/RootsClassic/assets/66848160/845bbbd0-8b7f-4a8c-a70f-af2035dc39d8)
With roots (main game menu):
![kdgRxYOM02](https://github.com/ZestyBlaze/RootsClassic/assets/66848160/a191465c-925f-49c0-aa93-30ffa7b812bb)

Usage in game Without roots:
![hCVgLp7zfY](https://github.com/ZestyBlaze/RootsClassic/assets/66848160/14321dfd-6896-43d8-929d-55f9a97e241c)
Usage in game With roots:
![vtB7K8kqTq](https://github.com/ZestyBlaze/RootsClassic/assets/66848160/dd1be5cc-350c-4e5a-a8d5-6d117fec566e)

That one mod, used more resources of biggest mods over 20+

**Comment by mindryder** [comment]
1.20.1

**Comment by ZestyBlaze** [comment]
It's not really a "memory leak" per se, its just that it's a big mod due to the library, I am working on compacting it down for future updates though

**Comment by mindryder** [comment]
One mod uses more 2GB RAM, just not memory leak?

**Comment by ZestyBlaze** [comment]
Memory Leak implies it's storing too much memory somewhere in the mod and not clearing it, this is more likely because it's a big mod with a lot of libraries that need trimming down
